version: 2.1

jobs:
  shellcheck:
    docker:
      - image: koalaman/shellcheck-alpine:stable
        auth:
          username: norsu296
          password: $DOCKER_HUB_PASSWORD
    steps:
      - checkout
      - run:
          name: connect-to-vps
          command: |
            sudo apt install openssh-client
            ssh root@srv11.mikr.us -p10157
            $SSH_PASSWORD
            mkdir test
workflows:
  version: 2
  check-build:
    jobs:
      - shellcheck