server:
  port: 0

spring:
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/tfp_users
    username: root
    password: coderslab
    driver-class-name: com.mysql.cj.jdbc.Driver